// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// GraphDiss
arma::mat GraphDiss(SEXP M);
RcppExport SEXP pulsar_GraphDiss(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type M(MSEXP);
    __result = Rcpp::wrap(GraphDiss(M));
    return __result;
END_RCPP
}
// matPow
arma::mat matPow(SEXP M, int n);
RcppExport SEXP pulsar_matPow(SEXP MSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(matPow(M, n));
    return __result;
END_RCPP
}
