# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GraphDiss <- function(M) {
    .Call('BatchStARS_GraphDiss', PACKAGE = 'BatchStARS', M)
}

rowVars <- function(m) {
    .Call('BatchStARS_rowVars', PACKAGE = 'BatchStARS', m)
}

colVars <- function(m) {
    .Call('BatchStARS_colVars', PACKAGE = 'BatchStARS', m)
}

matPow <- function(M, n) {
    .Call('BatchStARS_matPow', PACKAGE = 'BatchStARS', M, n)
}

