# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GraphDiss <- function(M) {
    .Call('pulsar_GraphDiss', PACKAGE = 'pulsar', M)
}

rowVars <- function(m) {
    .Call('pulsar_rowVars', PACKAGE = 'pulsar', m)
}

colVars <- function(m) {
    .Call('pulsar_colVars', PACKAGE = 'pulsar', m)
}

matPow <- function(M, n) {
    .Call('pulsar_matPow', PACKAGE = 'pulsar', M, n)
}

